name: ims_simulator

channels:
  # TODO: create alexandrovteam account on Anaconda.org and move stuff there
  - lomereiter # for ims cmdline tool

dependencies:
  - python=2.7
  - pip
  - numpy=1.10
  - cffi
  - scipy
  - toolz
  - dask
  - ims-cpp=0.1
  - pip:
    - cpyImagingMSpec==0.0.4
