name: ims_simulator

channels:
  # TODO: create alexandrovteam account on Anaconda.org and move stuff there
  - lomereiter # for ims and PFG cmdline tools

dependencies:
  - python=2.7
  - git
  - pip
  - numpy=1.10
  - cffi=1.5.2
  - scipy
  - toolz
  - dask
  - pandas
  - lxml
  - ims-cpp=0.2
  - PFG=0.1
  - matplotlib
  - pip:
    - cpyImagingMSpec==0.0.5
    - cpyMSpec==0.1.4
    - pyMSpec==0.1
    - wheezy.template
    - luigi
    - pyyaml
    - git+https://github.com/alexandrovteam/pyimzML.git@494f52e1519fcf820bf89f19f28344ddea45d3cf # TODO: package on PyPI
