---
  instrument:
    type: "fticr"   # currently 'fticr' and 'orbitrap' are supported
    res200: 250000  # resolution at m/z = 200
  imzml: "~/metabolomics/14_04_29_Regenwurm_pos_centroid.imzML"
  database:
    sum_formulas: "~/metabolomics/chebi_metabolites.txt"
    adducts:        # FIXME: negative adducts probably don't work yet
      - "+H"
      - "+K"
      - "+Na"
  factorization:
    rank: 30        # how many layers to generate
  noise:
    inflation: 1    # computed noise intensities are multiplied by this factor
